/* ===================== THE TIME-TRAVELER'S AGORA: KNOWLEDGE BASE (64 SAGES COMPLETE) ===================== */

const PHILS_DATA = [
    // ANCIENT (16)
    { id: 'socrates', mbti: 'ENTP', name: '소크라테스', era: 'ancient', quote: '"너 자신을 알라."', modifier: '무지의 깨달음', achievements: '산파술을 통한 진리 탐구, 서양 철학의 기초 확립', traits: '끊임없는 질문과 비판적 사고, 행동하는 지성', portrait: 'assets/portraits/socrates.png' },
    { id: 'plato', mbti: 'INFJ', name: '플라톤', era: 'ancient', quote: '"이데아를 보라."', modifier: '이상주의의 아버지', achievements: '아카데메이아 설립, 국가론 저술, 형이상학 체계 구축', traits: '영원한 본질 추구, 완벽한 질서와 도덕 강조', portrait: 'assets/portraits/plato.png' },
    { id: 'aristotle', mbti: 'ENTJ', name: '아리스토텔레스', era: 'ancient', quote: '"행복은 활동 속에 있다."', modifier: '지성의 거인', achievements: '논리학 체계화, 자연과학 및 정치학의 토대 마련', traits: '현실적 관찰과 분석, 체계적인 질서 추구', portrait: 'assets/portraits/aristotle.png' },
    { id: 'heraclitus', mbti: 'INTJ', name: '헤라클레이토스', era: 'ancient', quote: '"만물은 흐른다."', modifier: '변화의 현자', achievements: '생성 철학의 시초, 로고스 개념 확립', traits: '변화의 본질 통찰, 냉철한 직관과 사유', portrait: 'assets/portraits/heraclitus.png' },
    { id: 'laozi', mbti: 'INFP', name: '노자', era: 'ancient', quote: '"무위자연."', modifier: '순리의 스승', achievements: '도덕경 저술, 도가 철학의 창시', traits: '자연스러운 삶 추구, 인위적 강제 거부', portrait: 'assets/portraits/laozi.png' },
    { id: 'confucius', mbti: 'ISTJ', name: '공자', era: 'ancient', quote: '"배우고 때로 익히면 즐겁지 아니한가."', modifier: '조화의 성인', achievements: '유교 사상 확립, 교육의 보급 및 사회 윤리 정립', traits: '예우와 도덕 중시, 실천적 윤리 실현', portrait: 'assets/portraits/confucius.png' },
    { id: 'diogenes', mbti: 'ISTP', name: '디오게네스', era: 'ancient', quote: '"햇빛을 가리지 마시오."', modifier: '견유학파의 기인', achievements: '기성 관습의 파괴, 극단적 자활과 자유 실천', traits: '솔직하고 거침없는 행동, 소박함 속에 찾은 진리', portrait: 'assets/portraits/diogenes_portrait_art_1777083564401.png' },
    { id: 'epicurus', mbti: 'ISFP', name: '에피쿠로스', era: 'ancient', quote: '"우정과 고요함."', modifier: '평온의 추구자', achievements: '쾌락주의 철학 정립, 아타락시아 개념 제시', traits: '소박한 삶의 기쁨, 고통 없는 육체와 평온한 정신', portrait: 'assets/portraits/epicurus_portrait_art_1777083577489.png' },
    { id: 'marcus_aurelius', mbti: 'INFJ', name: '마르쿠스 아우렐리우스', era: 'ancient', quote: '"평온을 유지하라."', modifier: '명상하는 황제', achievements: '명상록 저술, 스토아 철학의 완성', traits: '철저한 자기 절제, 우주의 질서에 대한 수용', portrait: 'assets/portraits/marcus_aurelius.png' },
    { id: 'zhuangzi', mbti: 'INTP', name: '장자', era: 'ancient', quote: '"나비가 나인가, 내가 나비인가."', modifier: '절대 자유의 사유자', achievements: '제물론과 소요유의 사상 전개, 도가 철학의 심화', traits: '세속적 가치를 초월한 절대적 자유와 유희 추구', portrait: 'assets/portraits/zhuangzi.png' },
    { id: 'protagoras', mbti: 'ENFP', name: '프로타고라스', era: 'ancient', quote: '"인간은 만물의 척도다."', modifier: '상대주의의 선구자', achievements: '소피스트 학파의 창시, 지식의 상대성 주장', traits: '주관적 진리와 유연한 사고, 설득의 달인', portrait: 'assets/portraits/protagoras.png' },
    { id: 'aristippus', mbti: 'ESFP', name: '아리스티포스', era: 'ancient', quote: '"현재의 쾌락을 즐기라."', modifier: '향락의 현자', achievements: '키레네 학파 창시, 쾌락주의 윤리학의 기초 마련', traits: '현재의 즐거움에 집중하는 긍정적이고 개방적인 태도', portrait: 'assets/portraits/aristippus.png' },
    { id: 'mozi', mbti: 'ISFJ', name: '묵자', era: 'ancient', quote: '"겸애교상리."', modifier: '보편적 사랑의 실천가', achievements: '묵가 학파 창시, 차별 없는 사랑과 평화주의 제창', traits: '헌신적인 이타주의와 실천적 정의감', portrait: 'assets/portraits/mozi.png' },
    { id: 'mencius', mbti: 'ENFJ', name: '맹자', era: 'ancient', quote: '"인의의 수호자."', modifier: '인의의 수호자', achievements: '성선설 주장, 유교의 도덕 정치를 체계화', traits: '인간의 선함을 믿는 열정적인 교육자와 조언자', portrait: 'assets/portraits/mencius.png' },
    { id: 'hanfeizi', mbti: 'ESTJ', name: '한비자', era: 'ancient', quote: '"법은 엄격해야 한다."', modifier: '질서의 설계자', achievements: '법가 사상 집대성, 제왕학의 기틀 마련', traits: '객관적 규칙과 시스템을 중시하는 엄격한 관리자', portrait: 'assets/portraits/hanfeizi.png' },
    { id: 'epictetus', mbti: 'ESFJ', name: '에픽테토스', era: 'ancient', quote: '"네가 통제할 수 있는 것에 집중하라."', modifier: '실천적 스토아 학자', achievements: '스토아 윤리학의 실천적 전개, 노예에서 철학자가 된 극복의 아이콘', traits: '책임감 있고 타인을 배려하는 강인한 정신력', portrait: 'assets/portraits/epictetus.png' },

    // MEDIEVAL (16)
    { id: 'augustine', mbti: 'ISFJ', name: '아우구스티누스', era: 'medieval', quote: '"내 영혼의 고백."', modifier: '은총의 박사', achievements: '고백록 저술, 기독교 신학의 철학적 토대 구축', traits: '내면의 성찰과 신념에 대한 흔들림 없는 헌신', portrait: 'assets/portraits/augustine_portrait_art_v2_1777083604088.png' },
    { id: 'aquinas', mbti: 'ISTJ', name: '토마스 아퀴나스', era: 'medieval', quote: '"이성과 신앙은 둘 다 진리다."', modifier: '스콜라의 집대성자', achievements: '신학대전 저술, 이성과 신앙의 조화 실현', traits: '철저한 논리와 체계를 중시하는 신중한 학자', portrait: 'assets/portraits/aquinas_portrait_art_1777083618922.png' },
    { id: 'anselm', mbti: 'INFJ', name: '안셀무스', era: 'medieval', quote: '"이해하기 위해 믿는다."', modifier: '안토니아의 거인', achievements: '본체론적 신 존재 증명, 스콜라 철학의 아버지', traits: '깊은 통찰력과 이상적인 가치를 추구하는 사유자', portrait: 'assets/portraits/anselm_portrait_art_1777083631270.png' },
    { id: 'erasmus', mbti: 'ENFP', name: '에라스무스', era: 'medieval', quote: '"스스로 생각하라."', modifier: '인문주의의 거장', achievements: '우상예찬 저술, 종교개혁의 지적 토양 마련', traits: '권위에 저항하는 자유롭고 유연한 지성', portrait: 'assets/portraits/erasmus_portrait_art_1777083643942.png' },
    { id: 'ockham', mbti: 'INTP', name: '오컴', era: 'medieval', quote: '"단순한 것이 진리다."', modifier: '면도날의 사유자', achievements: '유명론 제창, 오컴의 면도날 법칙 확립', traits: '군더더기 없는 논리와 본질을 꿰뚫는 분석가', portrait: 'assets/portraits/ockham.png' },
    { id: 'abelard', mbti: 'ENFJ', name: '아벨라르', era: 'medieval', quote: '"의심은 질문을 낳는다."', modifier: '지적 열정의 신학자', achievements: '변증법적 신학 방법론 제시, 지적 용기와 신념의 상징', traits: '논쟁을 즐기며 사람들을 이끄는 카리스마 넘치는 리더', portrait: 'assets/portraits/abelard.png' },
    { id: 'machiavelli', mbti: 'ENTJ', name: '마키아벨리', era: 'medieval', quote: '"목적이 수단을 정당화한다."', modifier: '냉철한 군주론자', achievements: '정치학의 독립 선언, 군주론을 통한 현실 정치 분석', traits: '목표 달성을 위한 전략적 사고와 실행력', portrait: 'assets/portraits/machiavelli.png' },
    { id: 'avicenna', mbti: 'INTJ', name: '아비센나', era: 'medieval', quote: '"지식은 영혼의 빛이다."', modifier: '중세의 백과사전', achievements: '의학 정전 저술, 이슬람 철학의 전성기 주도', traits: '광범위한 지식을 체계화하는 냉철한 지성', portrait: 'assets/portraits/avicenna.png' },
    { id: 'francis', mbti: 'ISFP', name: '프란치스코', era: 'medieval', quote: '"평화의 도구가 되게 하소서."', modifier: '자연의 성자', achievements: '청빈과 자연 사랑의 실천, 평화와 조화의 메시지 전파', traits: '세상의 고통에 공감하며 조용히 실천하는 예술가', portrait: 'assets/portraits/francis.png' },
    { id: 'eckhart', mbti: 'INFP', name: '에크하르트', era: 'medieval', quote: '"신은 내 안에 있다."', modifier: '내면의 신비주의자', achievements: '영성 신학의 대가, 인간 영혼의 본질 탐구', traits: '깊은 내면의 가치와 이상을 소중히 여기는 몽상가', portrait: 'assets/portraits/eckhart.png' },
    { id: 'more', mbti: 'ESTJ', name: '토머스 모어', era: 'medieval', quote: '"유토피아를 꿈꾸라."', modifier: '신념의 정치가', achievements: '유토피아 저술, 신념을 지키기 위한 고귀한 희생', traits: '도덕적 원칙과 질서를 중시하는 책임감 있는 지도자', portrait: 'assets/portraits/more.png' },
    { id: 'bruno', mbti: 'ENTP', name: '지오르다노 브루노', era: 'medieval', quote: '"우주는 무한하다."', modifier: '불굴의 우주론자', achievements: '무한 우주설 제창, 권위에 굴하지 않는 자유로운 사유', traits: '새로운 가능성에 열광하며 기존 질서에 도전하는 혁신가', portrait: 'assets/portraits/bruno.png' },
    { id: 'hildegard', mbti: 'ESFJ', name: '힐데가르트', era: 'medieval', quote: '"생명의 광채를 보라."', modifier: '빛의 예언자', achievements: '의학, 음악, 신학 등 다방면의 천재성 발휘, 여성의 지성 입증', traits: '주변 사람들을 돌보고 사회에 기여하는 따뜻한 조력자', portrait: 'assets/portraits/hildegard.png' },
    { id: 'da_vinci', mbti: 'ISTP', name: '레오나르도 다 빈치', era: 'medieval', quote: '"아는 것이 사랑의 시작이다."', modifier: '만능의 천재', achievements: '르네상스 예술과 과학의 융합, 인류사 최고의 다재다능함', traits: '관찰과 실험을 즐기는 호기심 많은 탐험가', portrait: 'assets/portraits/da_vinci.png' },
    { id: 'borgia', mbti: 'ESTP', name: '체사레 보르자', era: 'medieval', quote: '"모 아니면 도."', modifier: '행동하는 야망가', achievements: '이탈리아 통일의 시도, 현실 정치의 과감한 실행', traits: '순간의 기회를 포착하는 민첩함과 과감한 추진력', portrait: 'assets/portraits/borgia.png' },
    { id: 'petrarch', mbti: 'ESFP', name: '페트라르카', era: 'medieval', quote: '"인간의 고통을 노래하라."', modifier: '서정적 인문주의자', achievements: '인문주의의 아버지, 칸초니에레를 통한 인간 감성 해방', traits: '삶의 아름다움과 감정을 풍부하게 표현하는 예술가', portrait: 'assets/portraits/petrarch.png' },

    // MODERN EARLY (16)
    { id: 'descartes', mbti: 'INTP', name: '데카르트', era: 'modern_early', quote: '"나는 생각한다, 고로 나는 존재한다."', modifier: '근대 철학의 아버지', achievements: '해석기하학 창시, 방법적 회의를 통한 근대 이성론의 토대 마련', traits: '논리적 분석과 근본적 원리를 중시하는 독립적 사유자', portrait: 'assets/portraits/descartes_portrait_art_1777083663077.png' },
    { id: 'spinoza', mbti: 'INFJ', name: '스피노자', era: 'modern_early', quote: '"신은 곧 자연이다."', modifier: '범신론의 사유자', achievements: '에티카 저술, 결정론적 세계관과 지적인 신애(神愛) 제시', traits: '세상의 질서를 직관적으로 통찰하고 내면의 평화를 추구하는 이상주의자', portrait: 'assets/portraits/spinoza_portrait_art_v2_1777083675634.png' },
    { id: 'kant', mbti: 'ISTJ', name: '칸트', era: 'modern_early', quote: '"정언명령을 따르라."', modifier: '도덕의 수호자', achievements: '비판 철학 체계 수립, 인식론과 윤리학의 코페르니쿠스적 전환', traits: '철저한 규율과 의무를 중시하는 성실하고 논리적인 학자', portrait: 'assets/portraits/kant_portrait_art_1777018777075.png' },
    { id: 'hume', mbti: 'ESTP', name: '흄', era: 'modern_early', quote: '"이성은 감정의 노예."', modifier: '경험론의 대가', achievements: '경험주의와 회의주의의 극치, 인성론 저술', traits: '관습과 경험을 중시하며 현재에 집중하는 현실적인 분석가', portrait: 'assets/portraits/hume_portrait_art_1777083688422.png' },
    { id: 'rousseau', mbti: 'ENFP', name: '루소', era: 'modern_early', quote: '"자연으로 돌아가라."', modifier: '고귀한 야만인의 대변인', achievements: '사회계약론 저술, 근대 민주주의와 교육학의 새로운 방향 제시', traits: '자유로운 영혼과 열정적인 감수성을 가진 혁명적 웅변가', portrait: 'assets/portraits/rousseau_portrait_art_v2_1777083699414.png' },
    { id: 'hobbes', mbti: 'ESTJ', name: '홉스', era: 'modern_early', quote: '"만인의 만인에 대한 투쟁."', modifier: '계약론의 실재주의자', achievements: '리바이어던 저술, 근대 정치 철학의 사회계약설 기초 확립', traits: '사회적 질서와 강력한 시스템을 중시하는 현실적인 전략가', portrait: 'assets/portraits/hobbes_portrait_art_v2_1777083713543.png' },
    { id: 'locke', mbti: 'ISTP', name: '존 로크', era: 'modern_early', quote: '"인간의 마음은 백지다."', modifier: '자유주의의 시조', achievements: '통치론 저술, 대의 민주주의와 자연권 사상의 확립', traits: '실용적인 경험과 개인의 자유를 존중하는 냉철한 관찰자', portrait: 'assets/portraits/locke_portrait_art_v2_1777083730248.png' },
    { id: 'voltaire', mbti: 'ENTP', name: '볼테르', era: 'modern_early', quote: '"관용을 지키라."', modifier: '관용의 지성', achievements: '계몽주의 사상의 보급, 표현의 자유와 관용의 가치 전파', traits: '재치 있고 날카로운 비판 정신을 가진 지적 선구자', portrait: 'assets/portraits/medieval_modern_batch_1_portraits_1777108030700.png' },
    { id: 'leibniz', mbti: 'INTJ', name: '라이프니츠', era: 'modern_early', quote: '"우주는 최선이다."', modifier: '보편의 천재', achievements: '미적분학 발견, 단자론을 통한 우주 질서 설명', traits: '세상의 모든 현상을 논리적 체계로 이해하려는 완벽주의자', portrait: 'assets/portraits/modern_early_batch_2_portraits_1777108054314.png' },
    { id: 'berkeley', mbti: 'INFJ', name: '버클리', era: 'modern_early', quote: '"존재는 지각됨이다."', modifier: '관념의 관조자', achievements: '주관적 관념론의 정립, 경험주의의 형이상학적 전개', traits: '현상의 이면과 정신적 본질을 깊이 있게 통찰하는 사유자', portrait: 'assets/portraits/modern_early_batch_2_portraits_1777108054314.png' },
    { id: 'hegel', mbti: 'ENTJ', name: '헤겔', era: 'modern_early', quote: '"이성적인 것은 현실적이다."', modifier: '변증법의 거장', achievements: '절대정신과 변증법적 역사 철학의 완성', traits: '거대한 역사의 흐름을 통제하고 이해하려는 강력한 지성', portrait: 'assets/portraits/modern_early_batch_2_portraits_1777108054314.png' },
    { id: 'wollstonecraft', mbti: 'ENFJ', name: '울스턴크래프트', era: 'modern_early', quote: '"인간은 평등하다."', modifier: '여성 권리의 선구자', achievements: '여성의 권리 옹호 저술, 현대 여성주의의 초석 마련', traits: '사회적 정의와 평등을 위해 헌신하는 열정적인 웅변가', portrait: 'assets/portraits/modern_early_batch_2_portraits_1777108054314.png' },
    { id: 'reid', mbti: 'ISFJ', name: '토머스 리드', era: 'modern_early', quote: '"상식은 철학의 기초다."', modifier: '상식의 수호자', achievements: '상식 학파의 창시, 극단적 회의주의에 대한 논리적 반박', traits: '전통과 보편적 가치를 지키려는 신중하고 성실한 수호자', portrait: 'assets/portraits/modern_early_batch_3_portraits_1777108076961.png' },
    { id: 'adam_smith', mbti: 'ISFP', name: '애덤 스미스', era: 'modern_early', quote: '"도덕적 공감이 중요하다."', modifier: '보이지 않는 손', achievements: '국부론 저술, 근대 경제학 체계 확립과 도덕 감정론 전개', traits: '타인의 감정에 공감하며 자유로운 개인의 선택을 존중하는 관찰자', portrait: 'assets/portraits/modern_early_batch_3_portraits_1777108076961.png' },
    { id: 'diderot', mbti: 'ESFP', name: '디드로', era: 'modern_early', quote: '"지식은 공유되어야 한다."', modifier: '백과의 지식인', achievements: '백과전서 편집 및 발간 주도, 지식의 대중화와 계몽 실천', traits: '다양한 분야에 호기심이 많고 에너지가 넘치는 활동가', portrait: 'assets/portraits/modern_early_batch_3_portraits_1777108076961.png' },
    { id: 'bentham', mbti: 'ESFJ', name: '제레미 벤담', era: 'modern_early', quote: '"최대 행복을 위하여."', modifier: '공리의 설계자', achievements: '공리주의 철학 정립, 사회 개혁과 법 제도 개선 제안', traits: '공동체의 조화와 구성원 전체의 행복을 추구하는 실무가', portrait: 'assets/portraits/modern_early_batch_3_portraits_1777108076961.png' },

    // MODERN LATE (16)
    { id: 'nietzsche', mbti: 'INTJ', name: '니체', era: 'modern_late', quote: '"신은 죽었다."', modifier: '망치의 철학자', portrait: 'assets/portraits/nietzsche_portrait_art_1777018760092.png' },
    { id: 'camus', mbti: 'ISFP', name: '카뮈', era: 'modern_late', quote: '"부조리 속에서 반항하라."', modifier: '부조리의 반항아', portrait: 'assets/portraits/camus_portrait_art_v2_1777083742812.png' },
    { id: 'kierkegaard', mbti: 'INFP', name: '키에르케고르', era: 'modern_late', quote: '"단독자로 서라."', modifier: '주체적 진리의 구도자', portrait: 'assets/portraits/modern_late_batch_1_portraits_v2_1777108098095.png' },
    { id: 'schopenhauer', mbti: 'INFJ', name: '쇼펜하우어', era: 'modern_late', quote: '"삶은 고통이다."', modifier: '의지의 염세주의자', portrait: 'assets/portraits/modern_late_batch_1_portraits_v2_1777108098095.png' },
    { id: 'sartre', mbti: 'ENTP', name: '사르트르', era: 'modern_late', quote: '"실존은 앞선다."', modifier: '자유의 사도', portrait: 'assets/portraits/modern_late_batch_1_portraits_v2_1777108098095.png' },
    { id: 'heidegger', mbti: 'INTP', name: '하이데거', era: 'modern_late', quote: '"존재를 들으라."', modifier: '존재의 탐구자', portrait: 'assets/portraits/modern_late_batch_1_portraits_v2_1777108098095.png' },
    { id: 'foucault', mbti: 'ENTP', name: '푸코', era: 'modern_late', quote: '"지식은 권력이다."', modifier: '광기의 역사학자', portrait: 'assets/portraits/modern_late_batch_2_portraits_v2_1777108119734.png' },
    { id: 'hannah_arendt', mbti: 'ENTJ', name: '한나 아렌트', era: 'modern_late', quote: '"악의 평범성."', modifier: '정치적 주체의 발견자', portrait: 'assets/portraits/modern_late_batch_2_portraits_v2_1777108119734.png' },
    { id: 'beauvoir', mbti: 'INFJ', name: '보부아르', era: 'modern_late', quote: '"여성은 만들어지는 것이다."', modifier: '제2의 성의 탐험가', portrait: 'assets/portraits/beauvoir_portrait_art_1777018793704.png' },
    { id: 'wittgenstein', mbti: 'INTJ', name: '비트겐슈타인', era: 'modern_late', quote: '"침묵하라."', modifier: '언어의 문법학자', portrait: 'assets/portraits/modern_late_batch_2_portraits_v2_1777108119734.png' },
    { id: 'marx', mbti: 'INTJ', name: '마르크스', era: 'modern_late', quote: '"세계를 변혁하라."', modifier: '변혁의 선언자', portrait: 'assets/portraits/modern_late_batch_2_portraits_v2_1777108119734.png' },
    { id: 'fromm', mbti: 'ENFJ', name: '에리히 프롬', era: 'modern_late', quote: '"사랑은 기술이다."', modifier: '사랑의 탐구자', portrait: 'assets/portraits/modern_late_batch_3_portraits_v2_1777108143287.png' },
    { id: 'derrida', mbti: 'INFP', name: '데리다', era: 'modern_late', quote: '"해체는 정의다."', modifier: '해체의 거장', portrait: 'assets/portraits/modern_late_batch_3_portraits_v2_1777108143287.png' },
    { id: 'popper', mbti: 'ESTJ', name: '칼 포퍼', era: 'modern_late', quote: '"열린 사회를 지키라."', modifier: '비판적 합리주의자', portrait: 'assets/portraits/modern_late_batch_3_portraits_v2_1777108143287.png' },
    { id: 'zizek', mbti: 'ENTP', name: '슬라보예 지젝', era: 'modern_late', quote: '"이데올로기는 안경이다."', modifier: '도발적 사유자', portrait: 'assets/portraits/modern_late_batch_3_portraits_v2_1777108143287.png' },
    { id: 'rawls', mbti: 'ISTJ', name: '존 롤스', era: 'modern_late', quote: '"정의는 공정함이다."', modifier: '공정의 설계자', portrait: 'assets/portraits/modern_late_batch_3_portraits_v2_1777108143287.png' }
];

const QUEST_DATA = {
    ancient: [
        { q: '아고라의 노인이 묻습니다. "지혜란 무엇입니까?"', a1: '나의 무지를 깨닫는 것', a2: '세상의 질서를 관찰하는 것', weight: { a1: { I: 2, N: 1 }, a2: { E: 2, S: 1 } } },
        { q: '"눈앞의 사물들은 진짜입니까, 이데아의 그림자입니까?"', a1: '보이지 않는 본질이 진짜다', a2: '만지는 현실이 진짜다', weight: { a1: { N: 2, J: 1 }, a2: { S: 2, P: 1 } } },
        { q: '"행복은 어디에 있습니까?"', a1: '이성적 덕의 실천', a2: '고통 없는 평온함', weight: { a1: { J: 2, T: 1 }, a2: { P: 2, F: 1 } } },
        { q: '"만물은 고정된 원소입니까, 흐르는 변화입니까?"', a1: '변하지 않는 원리가 있다', a2: '만물은 끊임없이 흐른다', weight: { a1: { S: 2, J: 1 }, a2: { N: 2, P: 1 } } },
        { q: '"정의는 무엇입니까?"', a1: '영혼의 조화로운 질서', a2: '강자의 유익함', weight: { a1: { I: 2, F: 1 }, a2: { E: 2, T: 1 } } },
        { q: '"국가는 누가 다스려야 합니까?"', a1: '지혜를 갖춘 철학자', a2: '자유로운 시민들', weight: { a1: { N: 2, J: 1 }, a2: { S: 2, P: 1 } } },
        { q: '"위험 앞에서 당신은?"', a1: '이성적으로 판단하여 후퇴', a2: '명예를 지키기 위해 돌진', weight: { a1: { T: 2, I: 1 }, a2: { F: 2, E: 1 } } },
        { q: '"우정이란?"', a1: '영혼의 완전한 결합', a2: '필요를 채우는 합리적 협력', weight: { a1: { F: 2, I: 1 }, a2: { T: 2, E: 1 } } },
        { q: '"자유란?"', a1: '욕망을 절제하는 내적 힘', a2: '행동의 방해를 받지 않는 것', weight: { a1: { J: 2, S: 1 }, a2: { P: 2, N: 1 } } },
        { q: '"운명이 당신을 억압한다면?"', a1: '평정심을 지키며 수용한다', a2: '저항하여 운명을 개척한다', weight: { a1: { I: 2, S: 1 }, a2: { E: 2, N: 1 } } },
        { q: '"죽음은?"', a1: '영혼의 자유로워지는 축복', a2: '감각이 사라지는 영원한 잠', weight: { a1: { N: 2, F: 1 }, a2: { S: 2, T: 1 } } },
        { q: '"어떤 삶을 살겠습니까?"', a1: '우주의 질서(Logos)에 순응', a2: '나만의 열정(Pathos)을 실현', weight: { a1: { J: 2, T: 1 }, a2: { P: 2, F: 1 } } }
    ],
    medieval: [
        { q: '"진리는 신의 계시입니까, 인간의 이성입니까?"', a1: '무조건적인 신앙과 계시', a2: '논리적인 증명과 토론', weight: { a1: { F: 2, J: 1 }, a2: { T: 2, P: 1 } } },
        { q: '"보편적 개념은 실제로 존재합니까?"', a1: '보편 실재가 존재한다', a2: '이름일 뿐이며 개별자만 실재한다', weight: { a1: { N: 2, J: 1 }, a2: { S: 2, P: 1 } } },
        { q: '"악은 왜 존재합니까?"', a1: '선의 결핍일 뿐이다', a2: '잘못된 자유의지의 결과다', weight: { a1: { I: 2, N: 1 }, a2: { E: 2, S: 1 } } },
        { q: '"신을 알기 위해서 무엇이 먼저입니까?"', a1: '믿음이 있어야 이해할 수 있다', a2: '의심하고 먼저 따져봐야 한다', weight: { a1: { F: 2, J: 1 }, a2: { T: 2, P: 1 } } },
        { q: '"수도원으로 들어가겠습니까?"', a1: '그렇다, 내면의 정화가 우선이다', a2: '아니다, 세상 속에서 실천하겠다', weight: { a1: { I: 2, F: 1 }, a2: { E: 2, T: 1 } } },
        { q: '"신의 법과 세속의 법이 충돌한다면?"', a1: '영원한 신의 법을 따른다', a2: '현실의 정당한 법을 따른다', weight: { a1: { J: 2, N: 1 }, a2: { P: 2, S: 1 } } },
        { q: '"죽음 이후의 삶은?"', a1: '천상의 복락 혹은 심판', a2: '자연의 에너지로 회귀', weight: { a1: { N: 2, F: 1 }, a2: { S: 2, T: 1 } } },
        { q: '"전통과 독창성 중 무엇이 중요합니까?"', a1: '오랜 세월 검증된 교회의 전통', a2: '개인의 주관적 영성 체험', weight: { a1: { S: 2, J: 1 }, a2: { N: 2, P: 1 } } },
        { q: '"인간의 본질은?"', a1: '은총이 필요한 죄인', a2: '이성을 갖춘 선한 가능성', weight: { a1: { I: 2, F: 1 }, a2: { E: 2, T: 1 } } },
        { q: '"토론을 즐기십니까?"', a1: '아니오, 신비한 침묵을 선호합니다', a2: '예, 엄밀한 논리 싸움을 즐깁니다', weight: { a1: { I: 2, N: 1 }, a2: { E: 2, S: 1 } } },
        { q: '"사랑(Agape)은?"', a1: '신성한 의무다', a2: '영원한 갈망이다', weight: { a1: { J: 2, T: 1 }, a2: { P: 2, F: 1 } } },
        { q: '"삶의 동력은?"', a1: '변치 않는 신앙', a2: '지적인 탐구', weight: { a1: { F: 2, J: 1 }, a2: { T: 2, P: 1 } } }
    ],
    modern_early: [
        { q: '"모든 것을 의심해보십시오. 확실한 것은 무엇입니까?"', a1: '생각하는 나의 존재', a2: '객관적인 수학적 질서', weight: { a1: { I: 2, N: 1 }, a2: { E: 2, S: 1 } } },
        { q: '"지식의 근원은 무엇입니까?"', a1: '타고난 이성적 관념', a2: '경험을 통한 습득', weight: { a1: { N: 2, J: 1 }, a2: { S: 2, P: 1 } } },
        { q: '"자연은 당신에게 어떤 의미입니까?"', a1: '신의 경이로운 섭리', a2: '정교하게 돌아가는 기계', weight: { a1: { F: 2, J: 1 }, a2: { T: 2, P: 1 } } },
        { q: '"국가는 왜 존재해야 합니까?"', a1: '강력한 힘으로 질서를 잡기 위해', a2: '개인의 자유를 계약으로 보장하기 위해', weight: { a1: { T: 2, J: 1 }, a2: { F: 2, P: 1 } } },
        { q: '"자유의지는 존재합니까?"', a1: '우리는 전적으로 자유롭다', a2: '물리적 인과법칙에 결정되어 있다', weight: { a1: { E: 2, J: 1 }, I: 2, P: 1 } },
        { q: '"실험을 반복하시겠습니까?"', a1: '예, 귀납적 사실이 중요하다', a2: '아니오, 연역적 사유가 중요하다', weight: { a1: { E: 2, S: 1 }, a2: { I: 2, N: 1 } } },
        { q: '"도덕의 기준은?"', a1: '누구에게나 예외 없는 의무', a2: '최대 다수의 최대 행복', weight: { a1: { J: 2, T: 1 }, a2: { P: 2, F: 1 } } },
        { q: '"신은 어떤 존재입니까?"', a1: '우주를 설계한 정교한 건축가', a2: '나의 고통을 아는 인격적 존재', weight: { a1: { T: 2, N: 1 }, a2: { F: 2, S: 1 } } },
        { q: '"감정은 이성에게 무엇입니까?"', a1: '다스리고 통제해야 할 대상', a2: '이성을 움직이게 하는 실제 주인', weight: { a1: { J: 2, T: 1 }, a2: { P: 2, F: 1 } } },
        { q: '"과학의 발전에 대해?"', a1: '인류를 낙원에서 인도할 빛', a2: '도구적 이성의 타락일 뿐', weight: { a1: { N: 2, E: 1 }, a2: { S: 2, I: 1 } } },
        { q: '"진리를 찾는 신뢰할 만한 방법은?"', a1: '수학적 연역법', a2: '관찰에 근거한 귀납법', weight: { a1: { J: 2, N: 1 }, a2: { P: 2, S: 1 } } },
        { q: '"미래의 세계는?"', a1: '투명한 이성의 시대', a2: '억압 없는 자유의 시대', weight: { a1: { T: 2, J: 1 }, a2: { F: 2, P: 1 } } }
    ],
    modern_late: [
        { q: '"신은 죽었습니다. 이제 무엇을 따르겠습니까?"', a1: '과거를 파괴하고 나만의 가치 창조', a2: '전통의 미덕을 지키며 질서 유지', weight: { a1: { N: 2, P: 1 }, a2: { S: 2, J: 1 } } },
        { q: '"부조리한 우주를 보며 어떤 기분이 듭니까?"', a1: '허무를 직시하고 당당히 반항한다', a2: '보이지 않는 거대한 의지가 있다고 믿는다', weight: { a1: { N: 2, T: 1 }, a2: { S: 2, F: 1 } } },
        { q: '"어떤 인간이 되고 싶습니까?"', a1: '한계를 극복하는 강인한 초인', a2: '고통받는 자를 돌보는 연민의 인간', weight: { a1: { E: 2, T: 1 }, a2: { I: 2, F: 1 } } },
        { q: '"현대 문명에서 가장 두려운 것은?"', a1: '시스템의 부속품이 되는 것', a2: '군중 속에서 나를 잃어버리는 것', weight: { a1: { I: 2, N: 1 }, a2: { E: 2, S: 1 } } },
        { q: '"삶의 본질은?"', a1: '본질은 고통이며 쾌락은 잠시뿐이다', a2: '나 자신이 긍정한다면 충분히 즐겁다', weight: { a1: { I: 2, T: 1 }, a2: { E: 2, F: 1 } } },
        { q: '"당신을 정의하는 것은?"', a1: '주어진 상황과 타고난 기질', a2: '내가 매 순간 내리는 자유로운 선택', weight: { a1: { S: 2, J: 1 }, a2: { N: 2, P: 1 } } },
        { q: '"언어는 진리의 집입니까, 감옥입니까?"', a1: '진리를 가두는 한계일 뿐이다', a2: '진리를 드러내는 유일한 통로다', weight: { a1: { I: 2, N: 1 }, a2: { E: 2, S: 1 } } },
        { q: '"타인은 당신에게?"', a1: '나의 자유를 감시하는 지옥이다', a2: '함께 책임져야 할 동반자', weight: { a1: { T: 2, I: 1 }, a2: { F: 2, E: 1 } } },
        { q: '"죽음은?"', a1: '실존을 깨우는 비장하고 엄숙한 공포', a2: '부질없지만 담담히 받아들임', weight: { a1: { J: 2, N: 1 }, a2: { P: 2, S: 1 } } },
        { q: '"기계가 인간을 대체한다면?"', a1: '인간의 존엄은 대체 불가능하다', a2: '시스템과 진화하며 적응하하겠다', weight: { a1: { F: 2, I: 1 }, a2: { T: 2, E: 1 } } },
        { q: '"무엇이 당신을 움직입니까?"', a1: '권력과 승리의 의지', a2: '조용한 관조와 해탈', weight: { a1: { E: 2, T: 1 }, a2: { I: 2, F: 1 } } },
        { q: '"어떤 세계를 창조하시겠습니까?"', a1: '영원히 되풀이되어도 당당한 세계', a2: '찰나의 유일한 가치가 빛나는 세계', weight: { a1: { J: 2, N: 1 }, a2: { P: 2, S: 1 } } }
    ]
};
